### PR TITLE
improved french translation

### PR DESCRIPTION
**Pull request by M2ck**

### CODE REVIEW

**Comment by M2ck** [comment]
Oops someone for improve title from my second commit, lol sorry about that.

**Comment by BramBonne** [comment]
Thank you!

**Comment by M2ck** [comment]
You're welcome!
Question about "anonymous usage statistics" option, I don't find it on my device. Possible bug or this option has been removed meanwhile?

**Comment by BramBonne** [comment]
This option has indeed been removed. I didn't want anyone to have any privacy concerns when installing the app :-)

**Comment by M2ck** [comment]
Ok I understand, thanks for your quick reply.

**Pull request merged**
